name: intro_slider
description: Simple and configurable app introduction slider for Flutter
author:
  - Duy Tran <tranquangduy7994@gmail.com>
homepage: https://github.com/duytq94/flutter-intro-slider
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.dfa.introslider
    pluginClass: IntroSliderPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"